version: '3.9'

services:
  web:
    container_name: pvpoke
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8033:80
    volumes:
      - ../src:/var/www/html/pvpoke/src