version: '3.9'

services:
  web:
    container_name: pvpoke
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ../src:/var/www/html/pvpoke/src